### ISSUE TITLE
libmagic randomly reporting incorrect mime types?

### ISSUE THREAD

**Issue by jamiesonbecker** [threatstack/libmagic#1]
libmagic randomly reporting incorrect mime types?

[root@localhost css]# file -i main-style.css
main-style.css: text/x-c++; charset=us-ascii
[root@ localhost css]# cat /etc/redhat-release
CentOS release 6.6 (Final)

See bug reports in downstream:
https://github.com/ahupp/python-magic/issues/75#issuecomment-78340589
https://github.com/s3tools/s3cmd/issues/198#issuecomment-21835205

**Comment by jamiesonbecker** [comment]
I don't see this behavior in Debian 7.

**Comment by ellzey** [comment]
This is just a mirror of libmagic. This org does not maintain it.

**Comment by jamiesonbecker** [comment]
Ah, sorry :)
