### ISSUE TITLE
Add link to latest sources

### ISSUE THREAD

**Issue by petk** [threatstack/libmagic#8]
Hello, finding the libmagic sources is not that trivial. Maybe adding a link to the latest library sources might help finding the real location of this library and if it is still maintained and how to contribute patches, fixes, pull requests etc.

Thanks.

**Comment by stokito** [comment]
Here is an official mirror for file and libmagic  https://github.com/file/file
To build and install you need to execute:
```
autoreconf -f -i
make
sudo make install
```

**Comment by petk** [comment]
Thank you so much for your help. Closing this as resolved then...
